### ISSUE TITLE
Numpy casting error when applying FFT along non-float data

### ISSUE THREAD

**Issue by mgiammar** [deepanshs/csdmpy#73]
Did you find a bug? Please help us improve by fill out the sections below. 👍

Creating a CSDM object from an integer numpy array causes a `same_kind` casting error in numpy. Internally, csdmpy is trying to divide an integer array by a float array; this is disallowed in numpy when `same_kind` is set to `True`

```
import csdmpy as cp
import numpy as np
dataset = cp.as_csdm(np.arange(20))  # Integer type by default
dataset.fft()
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/.../csdmpy/csdmpy/csdm.py", line 1144, in fft
    return fft(self, axis)
  File "/Users/.../csdmpy/csdmpy/numpy_wrapper/__init__.py", line 63, in fft
    item.subtype._components[slice_] /= scale_factor
numpy.core._exceptions._UFuncOutputCastingError: Cannot cast ufunc 'divide' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'with casting rule 'same_kind'
```

**Expected behavior**

Successful Fourier transform without error

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS
- Python version: 3.10.8
- `csdmpy` version: **0.6.dev2**

**Additional context**

Casting the original numpy array to a float type resolves this issue.

```
import csdmpy as cp
import numpy as np
dataset = cp.as_csdm(np.arange(20, dtype=np.float64))  # Now a float type
dataset.fft()
```

**Comment by deepanshs** [comment]
I don't think this is a bug. FFT of integers will cast to float. If you are going to do FFT, you should start with a float array.

**Comment by mgiammar** [comment]
Closing issue since not a bug.
